### ISSUE TITLE
dkimsign.pl: default algorithm and documentation

### ISSUE THREAD

**Issue by gregoa** [fastmail/mail-dkim#15]
In Debian, we have the following bug report about scripts/dkimsign.pl (shipped as dkimproxy-sign):
https://bugs.debian.org/961472
which, in two parts, suggest to change the default algorithm from rsa-sha1 to rsa-sha256, referring to RFC 8301, and also notes that the POD in the script only documents part of the actual options.

Thanks for considering,  
gregor, Debian Perl Group

**Comment by notbrokenjemma** [comment]
Will be fixed in next release, thanks.

**Comment by gregoa** [comment]
Excellent, thank you!
