### ISSUE TITLE
opendkim and Mail::DKIM disagree

### ISSUE THREAD

**Issue by Thermi** [fastmail/mail-dkim#2]
Hi,

I (and a lot of other people) are using Mail::DKIM as part of SpamAssassin to verify the DKIM signatures on mails. SpamAssassin logs that the signatures on my mails were faulty, but opendkim says they're okay (but opendkim-testmsg fails to parse the DKIM headers, so I'm even further down the rabbit hole).

Is there some way to make this packet tell me why it regards the signature as valid?

**Comment by brong** [comment]
Do you have an example message that can be used as a testcase?

**Comment by Thermi** [comment]
I sent you an email when you asked for it, because we obviously need a verbatim one. Did you get it?

**Comment by notbrokenjemma** [comment]
Cannot reproduce without test data
