### ISSUE TITLE
Verify DKIM ed25519 crash

### ISSUE THREAD

**Issue by atueting** [fastmail/mail-dkim#24]
Hello,

I'm getting a crash on FreeBSD 13.2 while checking DKIM signature in Amavisd-new.  Stack trace attached..

Mail-DKIM-1.20230911
amavisd-new-2.12.2_1,1
[AmavisCrash.txt](https://github.com/fastmail/mail-dkim/files/13217647/AmavisCrash.txt)

Regards,
Armin.

**Comment by notbrokenjemma** [comment]
This is coming from Crypt::PK::Ed25519, I have opened an issue there.
