### ISSUE TITLE
DKIM failed when subject too long

### ISSUE THREAD

**Issue by perler-at** [fastmail/mail-dkim#31]
Hello!

I have noticed that the DKIM test (https://www.appmaildev.com/en/dkim) fails if the subject is too long. Specifically, this happens when the subject in the mail body is two lines long. Is there a solution for this?

Best regards, Perler

**Comment by notbrokenjemma** [comment]
Hi,
Do you have an example message where this happened?

**Comment by perler-at** [comment]
Yes:

```
PASS:
Subject: =?UTF-8?Q?=F0=9F=92=B6_Flexibler_Ratenplan?=

FAIL:
Subject: =?UTF-8?Q?=F0=9F=92=B6_Flexibler_Ratenplan_f=C3=BCr_die_neue_Instagram_Ma?=
  =?UTF-8?Q?sterclass?=
```

I just changed the subject of the mail.

**Comment by notbrokenjemma** [comment]
I would need the entire message, not just the subject.
